services:
  db:
    image: mysql:8.0.45
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: academic_manager
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
    volumes:
      - mysql-data:/var/lib/mysql
      - ./scripts:/docker-entrypoint-initdb.d

  api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./uploads:/uploads

volumes:
  mysql-data: